evaluation:
  cost_false_positive: 5.0
features:
  customer_windows:
  - 1
  - 7
  - 30
  delay_period: 7
  terminal_windows:
  - 1
  - 7
  - 30
model:
  exclude_cols_from_features:
  - TRANSACTION_ID
  - TX_DATETIME
  - CUSTOMER_ID
  - TERMINAL_ID
  - TX_FRAUD
  - TX_FRAUD_SCENARIO
  - TX_TIME_SECONDS
  - TX_TIME_DAYS
  lightgbm_params:
    colsample_bytree: 0.8
    learning_rate: 0.05
    max_depth: 6
    min_child_samples: 50
    n_estimators: 300
    n_jobs: -1
    num_leaves: 31
    random_state: 42
    subsample: 0.8
  target_col: TX_FRAUD
simulator:
  n_customers: 10000
  n_terminals: 20000
  nb_days: 180
  radius: 5
  random_seed: 42
  start_date: '2018-04-01'
split:
  test_start_day: 127
  train_end_day: 120
