"""initial_schema

Revision ID: abd6341e60c6
Revises: 
Create Date: 2026-08-27 02:53:13.272216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abd6341e60c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('holdout_set_version', sa.String(), nullable=False),
    sa.Column('holdout_set_hash', sa.String(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('is_champion', sa.Boolean(), nullable=False),
    sa.Column('report_url', sa.String(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_evaluations_model_name'), 'risk_evaluations', ['model_name'], unique=False)
    op.create_table('risk_tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('fp_cost_per_unit', sa.Numeric(), nullable=False),
    sa.Column('fn_cost_per_unit', sa.Numeric(), nullable=False),
    sa.Column('policy_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['risk_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_users_email'), 'risk_users', ['email'], unique=True)
    op.create_index(op.f('ix_risk_users_tenant_id'), 'risk_users', ['tenant_id'], unique=False)
    op.create_table('risk_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('metadata_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['risk_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['risk_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source', 'source_id', name='uq_tenant_source_id')
    )
    op.create_index('idx_cases_open', 'risk_cases', ['tenant_id', 'deadline'], unique=False, postgresql_where=sa.text("status NOT IN ('WON', 'LOST', 'EXPIRED', 'ACCEPTED_LOSS')"))
    op.create_index(op.f('ix_risk_cases_source'), 'risk_cases', ['source'], unique=False)
    op.create_index(op.f('ix_risk_cases_status'), 'risk_cases', ['status'], unique=False)
    op.create_index(op.f('ix_risk_cases_tenant_id'), 'risk_cases', ['tenant_id'], unique=False)
    op.create_table('risk_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['risk_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['risk_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['risk_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_audit_logs_case_id'), 'risk_audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_risk_audit_logs_tenant_id'), 'risk_audit_logs', ['tenant_id'], unique=False)
    op.create_table('risk_chargebacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('arn', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(), nullable=False),
    sa.Column('evidence_bundle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('representment_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('win_probability', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['risk_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['risk_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_arn', 'risk_chargebacks', ['tenant_id', 'arn'], unique=True)
    op.create_index(op.f('ix_risk_chargebacks_case_id'), 'risk_chargebacks', ['case_id'], unique=False)
    op.create_index(op.f('ix_risk_chargebacks_tenant_id'), 'risk_chargebacks', ['tenant_id'], unique=False)
    # Enable RLS and create policies
    op.execute("ALTER TABLE risk_cases ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY tenant_isolation_cases ON risk_cases USING (tenant_id = current_setting('app.current_tenant')::uuid)")
    
    op.execute("ALTER TABLE risk_chargebacks ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY tenant_isolation_chargebacks ON risk_chargebacks USING (tenant_id = current_setting('app.current_tenant')::uuid)")
    
    op.execute("ALTER TABLE risk_audit_logs ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY tenant_isolation_audit_logs ON risk_audit_logs USING (tenant_id = current_setting('app.current_tenant')::uuid)")
    
    op.execute("ALTER TABLE risk_users ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY tenant_isolation_users ON risk_users USING (tenant_id = current_setting('app.current_tenant')::uuid)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_chargebacks_tenant_id'), table_name='risk_chargebacks')
    op.drop_index(op.f('ix_risk_chargebacks_case_id'), table_name='risk_chargebacks')
    op.drop_index('idx_tenant_arn', table_name='risk_chargebacks')
    op.drop_table('risk_chargebacks')
    op.drop_index(op.f('ix_risk_audit_logs_tenant_id'), table_name='risk_audit_logs')
    op.drop_index(op.f('ix_risk_audit_logs_case_id'), table_name='risk_audit_logs')
    op.drop_table('risk_audit_logs')
    op.drop_index(op.f('ix_risk_cases_tenant_id'), table_name='risk_cases')
    op.drop_index(op.f('ix_risk_cases_status'), table_name='risk_cases')
    op.drop_index(op.f('ix_risk_cases_source'), table_name='risk_cases')
    op.drop_index('idx_cases_open', table_name='risk_cases', postgresql_where=sa.text("status NOT IN ('WON', 'LOST', 'EXPIRED', 'ACCEPTED_LOSS')"))
    op.drop_table('risk_cases')
    op.drop_index(op.f('ix_risk_users_tenant_id'), table_name='risk_users')
    op.drop_index(op.f('ix_risk_users_email'), table_name='risk_users')
    op.drop_table('risk_users')
    op.drop_table('risk_tenants')
    op.drop_index(op.f('ix_risk_evaluations_model_name'), table_name='risk_evaluations')
    op.drop_table('risk_evaluations')
    # ### end Alembic commands ###
